# Generated by Django 5.2.9 on 2026-01-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionmodel',
            name='classifier_type',
            field=models.CharField(choices=[('knn', 'k-Nearest Neighbors'), ('centroid', 'Centroid-based')], default='knn', max_length=20),
        ),
    ]
